routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('commands/{command}', function($command) {
    try {
        \Illuminate\Support\Facades\Artisan::call($command);
    } catch(\Exception $e){
        dd($e->getMessage());
    }

    echo \Illuminate\Support\Facades\Artisan::output();
});

Route::get('image_show/{filename}', 'ImageController@displayImage')->name('image.show');

// ROTAS DO SITE
Route::group(['prefix'=>'/', 'namespace' => 'Home', 'as' => 'home.'], function() {
    Route::get('/', ['uses' => 'SiteController@index'])->name('index');
    Route::post('/busca', ['uses' => 'SiteController@search'])->name('search');
    Route::get('{client}/detalhes/', ['uses' => 'SiteController@details'])->name('details');
    Route::get('projeto/{slug}', ['uses' => 'SiteController@projectDetail'])->name('project.details');
    Route::get('/contato', ['uses' => 'SiteController@contact'])->name('contact');
    Route::get('/quem-somos', ['uses' => 'SiteController@about'])->name('about');
    Route::get('/projetos', ['uses' => 'SiteController@projects'])->name('projects');
    Route::get('/registro', ['uses' => 'SiteController@register'])->name('register');
    Route::get('/categorias', ['uses' => 'SiteController@categories'])->name('categories');
    Route::get('/categorias/{slug}', ['uses' => 'SiteController@category'])->name('category');
    Route::get('politica-de-privacidade', ['uses' => 'SiteController@policies'])->name('policies');
    Route::get('termos-de-uso', ['uses' => 'SiteController@terms'])->name('terms');
});



Auth::routes();

// ROTAS DO DASH ADMIN
Route::group(['prefix'=>'/admin',  'namespace' => 'Admin', 'middleware' => ['auth']], function() {

    Route::get('/', ['as' => 'admin.dash', 'uses' => 'AdminController@index']);

    Route::resource('/clients', 'ClientsController');

    Route::resource('/advertisements', 'AdvertisementsController');

    Route::resource('/users', 'UsersController');

    Route::resource('/payments', 'PaymentsController');

    Route::resource('/categories', 'CategoriesController');

    Route::resource('/contracts', 'ContractsController');

    Route::resource('/catalogs', 'CatalogsController');

    Route::resource('/configs', 'ConfigsController');

    Route::resource('/usefuls', 'UsefulsController');

    Route::resource('/projects', 'ProjectsController');
});


Route::get('/home', 'HomeController@index')->name('home');

app/Models/Advertsement.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Advertsement extends Model
{
    protected  $fillable = [
        'id',
        'name',
        'details',
        'amount'
    ];

    public function getApplications()
    {
        return $this->belongsTo(AdvertsementHasApplication::class, 'id', 'advertsements_id');
    }

    public function applications()
    {
        return $this->belongsToMany(AdvertsementHasApplication::class, 'advertsements_has_applications', 'advertsements_id', 'applications_id')->withTimestamps();
    }

    public function monetary(){
        return number_format($this->amount, 2,',', '.');
    }

    public static function convertMonetary($args){

        $numberConvertedExp = str_replace(".", "", $args);
        return number_format( floatval($numberConvertedExp), 2, '.', '');
    }

    public function setApplications($args){
        $this->applications()->sync($args);
    }

    public function isAttached($itemId){
        $checkApplication = AdvertsementHasApplication::where('advertsements_id',$this->id)->where('applications_id', $itemId)->first();

        if ($checkApplication){
            return true;
        }
    }


}

resources/views/admin/advertsements/create.blade.php
@extends('layouts.admin.app')
@section('title', 'Cadastro')
@section('content-header')
    Cadastrar novo plano de negócios
@endsection

@section('content')

    <!-- Main content -->
    <div class="row">
        <div class="col-xs-12">

            <div class="box box-primary">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="POST" action="{{ route('advertisements.store') }}">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <label for="name">Nome / apelido</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" placeholder="Nome para identificação do plano">
                        </div>
                        <div class="form-group">
                            <label for="name">Detalhes</label>
                            <textarea class="form-control" rows="3" name="details" value="{{ old('details') }}" placeholder="Descrição do plano de negócios"></textarea>
                        </div>

                        <div class="form-check">
                            <label for="name">Serviços</label><br>
                            @foreach ($applications as $application)
                                <input type="checkbox" class="form-check-input" value="{{ $application->id }}" name="application[]" id="{{ $application->id }}">
                                <label class="form-check-label" for="{{ $application->id }}">{{ $application->name }}</label><Br>
                            @endforeach
                        </div>

                        <div class="form-group">
                            <label for="name">Valor</label>
                            <input type="text" class="form-control money" id="amount" value="{{ old('amount') }}" name="amount" placeholder="Valor ">
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Salvar" class="btn btn-info btn-block">

                        </div>

                    </div>
                </form>


        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
@push('scripts')
            <script src="{{ asset("js/jquery.inputmask.js") }}"></script>
            <script src="{{ asset("js/jquery.inputmask.date.extensions.js") }}"></script>
            <script src="{{ asset("js/jquery.inputmask.extensions.js") }}"></script>

            <script>
                $(function () {
                    //Datemask dd/mm/yyyy
                    $('#money').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
                    //Datemask2 mm/dd/yyyy
                    $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
                    //Money Euro
                    $('[data-mask]').inputmask()


                })
            </script>
@endpush
@endsection

resources/views/admin/advertsements/index.blade.php
@extends('layouts.admin.app')
@section('title', 'Cadastro')
@section('content-header')
    Plano de negócios
@endsection

@section('content')

    <!-- Main content -->
        <div class="row">
            <div class="col-xs-12">

                <div class="box">
                    <div class="box-header">
                        <a href="{{ route('advertisements.create') }}" class="btn btn-block btn-info">  <i class="fa fa-edit"></i> ADICIONAR UM NOVO PLANO DE NEGÓCIO</a>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Detalhes</th>
                                <th>Valor</th>
                                <th>Ações</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($advertsements as $advertsement)
                            <tr>
                                <td>{{ $advertsement->name }}</td>
                                <td>{{ $advertsement->details }}</td>
                                <td>{{ $advertsement->amount }}</td>
                                <td>
                                    <a class="btn btn-sm" href="{{ route('advertisements.edit', $advertsement->id) }}"> <i class="fa fa-edit"></i>  </a>
                                    <a class="btn btn-sm"  data-toggle="modal" data-target="#iconModal-{{ $advertsement->id }}"> <i class="fa fa-trash"></i>  </a>
                                    <a class="btn btn-sm" href="{{ route('advertisements.show', $advertsement->id) }}"> <i class="fa fa-eye"></i>  </a>
                                    <div class="modal fade text-xs-left" id="iconModal-{{ $advertsement->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                    <h4 class="modal-title" id="myModalLabel2"><i class="icon-warning2"></i> Confirma operação</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Você tem certeza que quer <strong>apagar</strong> esta regra ?</p>

                                                </div>
                                                <div class="modal-footer">
                                                    <form method="POST" action="{{ route('advertisements.destroy', $advertsement->id) }}">
                                                        @method('DELETE')
                                                        @csrf
                                                        <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Fechar</button>
                                                        <button type="submit" class="btn btn-outline-primary">Deletar</button>
                                                    </form>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    @push('scripts')
        @if (session('message'))
            {!! toastr()->info(session('message'), 'Atenção')->render() !!}
        @endif
    @endpush
    @endsection