routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('commands/{command}', function($command) {
    try {
        \Illuminate\Support\Facades\Artisan::call($command);
    } catch(\Exception $e){
        dd($e->getMessage());
    }

    echo \Illuminate\Support\Facades\Artisan::output();
});

Route::get('image_show/{filename}', 'ImageController@displayImage')->name('image.show');

// ROTAS DO SITE
Route::group(['prefix'=>'/', 'namespace' => 'Home', 'as' => 'home.'], function() {
    Route::get('/', ['uses' => 'SiteController@index'])->name('index');
    Route::post('/busca', ['uses' => 'SiteController@search'])->name('search');
    Route::get('{client}/detalhes/', ['uses' => 'SiteController@details'])->name('details');
    Route::get('projeto/{slug}', ['uses' => 'SiteController@projectDetail'])->name('project.details');
    Route::get('/contato', ['uses' => 'SiteController@contact'])->name('contact');
    Route::get('/quem-somos', ['uses' => 'SiteController@about'])->name('about');
    Route::get('/projetos', ['uses' => 'SiteController@projects'])->name('projects');
    Route::get('/registro', ['uses' => 'SiteController@register'])->name('register');
    Route::get('/categorias', ['uses' => 'SiteController@categories'])->name('categories');
    Route::get('/categorias/{slug}', ['uses' => 'SiteController@category'])->name('category');
    Route::get('politica-de-privacidade', ['uses' => 'SiteController@policies'])->name('policies');
    Route::get('termos-de-uso', ['uses' => 'SiteController@terms'])->name('terms');
});



Auth::routes();

// ROTAS DO DASH ADMIN
Route::group(['prefix'=>'/admin',  'namespace' => 'Admin', 'middleware' => ['auth']], function() {

    Route::get('/', ['as' => 'admin.dash', 'uses' => 'AdminController@index']);

    Route::resource('/clients', 'ClientsController');

    Route::resource('/advertisements', 'AdvertisementsController');

    Route::resource('/users', 'UsersController');

    Route::resource('/payments', 'PaymentsController');

    Route::resource('/categories', 'CategoriesController');

    Route::resource('/contracts', 'ContractsController');

    Route::resource('/catalogs', 'CatalogsController');

    Route::resource('/configs', 'ConfigsController');

    Route::resource('/usefuls', 'UsefulsController');

    Route::resource('/projects', 'ProjectsController');
});


Route::get('/home', 'HomeController@index')->name('home');

app/Models/Catalog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Attachment;

class Catalog extends Model
{
    protected $fillable = [
        'name',
        'client_id',
    ];

    public function attachments(){
        return $this->morphMany(Attachment::class, 'attachmentable');
    }

    public function client(){
        return $this->belongsTo(Client::class, 'client_id');
    }

    public function sendFiles($files){

        foreach ($files as $file){
            $path = $file->store('attachments');
            $this->attachments()->create(['path' => $path]);
        }

        return true;
    }

}

app/Http/Controllers/Admin/CatalogsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Attachment;
use App\Models\Catalog;
use App\Models\Client;
use Illuminate\Http\Request;

class CatalogsController extends Controller
{

    public function index()
    {
        $catalogs = Catalog::all();
        return view('admin.catalogs.index', compact('catalogs'));
    }


    public function create()
    {
        $clients = Client::all();
        return view('admin.catalogs.create', compact('clients'));
    }


    public function store(Request $request)
    {

       $catalog = Catalog::create($request->all());

       $catalog->sendFiles($request->attachments);

       return redirect(route('catalogs.index'))->with('message', 'Catálogo lançado com sucesso !');
    }


    public function show($id)
    {
        //
    }


    public function edit(Catalog $catalog)
    {
       return view('admin.catalogs.edit', compact('catalog'));


    }


    public function update(Request $request, $id)
    {
        //
    }


    public function destroy(Catalog $catalog)
    {
        $catalog->delete();

        return redirect(route('catalogs.index'))->with('message', 'Catálogo apagado com sucesso !');

    }
}

resources/views/admin/catalogs/create.blade.php
@extends('layouts.admin.app')
@section('title', 'Cadastro')
@push('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
    <!-- if using RTL (Right-To-Left) orientation, load the RTL CSS file after fileinput.css by uncommenting below -->
    <!-- link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/css/fileinput-rtl.min.css" media="all" rel="stylesheet" type="text/css" /-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!-- piexif.min.js is needed for auto orienting image files OR when restoring exif data in resized images and when you
        wish to resize images before upload. This must be loaded before fileinput.min.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/piexif.min.js" type="text/javascript"></script>
    <!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview.
        This must be loaded before fileinput.min.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/sortable.min.js" type="text/javascript"></script>
    <!-- purify.min.js is only needed if you wish to purify HTML content in your preview for
        HTML files. This must be loaded before fileinput.min.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/purify.min.js" type="text/javascript"></script>
    <!-- popper.min.js below is needed if you use bootstrap 4.x. You can also use the bootstrap js
       3.3.x versions without popper.min.js. -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- bootstrap.min.js below is needed if you wish to zoom and preview file content in a detail modal
        dialog. bootstrap 4.x is supported. You can also use the bootstrap js 3.3.x versions. -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- the main fileinput plugin file -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/fileinput.min.js"></script>
    <!-- optionally if you need a theme like font awesome theme you can include it as mentioned below -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/themes/fa/theme.js"></script>
    <!-- optionally if you need translation for your language then include  locale file as mentioned below -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/locales/(lang).js"></script>
@endpush
@section('content-header')
   Cadastrar um novo catálogo
@endsection

@section('content')

    <!-- Main content -->
    <div class="row">
        <div class="col-xs-12">

            <div class="box box-primary">

                @if ($errors->any())
                    <div class="card-body">
                        <div class="callout callout-danger">
                            <h5>Preencha corretamente os campos.</h5>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
            @endif

            <!-- /.box-header -->
                <!-- form start -->
                <form method="post" action="{{ route('catalogs.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <label for="name">Nome da galeria / Título</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" placeholder="Título da galeria">
                        </div>

                        <div class="form-group">
                            <label for="name">Nome do cliente</label>
                            <select name="client_id" class="form-control select2" style="width: 100%;">
                                <option selected="selected">Selecione</option>
                                @foreach ($clients as $client)
                                    <option value="{{ $client->id }}">{{ $client->name }} ({{$client->document}})</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <input id="input-b1" name="attachments[]" type="file" class="file" multiple data-browse-on-zone-click="true">
                        </div>

                        <br><Br><Br>
                    <input type="submit" class="btn btn-block btn-success" value="CADASTRAR">
                </form>


            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    @push('scripts')
        @if ($errors->any())
            {!! toastr()->error('Houve um erro no cadastro', 'Atenção')->render() !!}
        @endif
    @endpush
@endsection

resources/views/admin/catalogs/edit.blade.php
@extends('layouts.admin.app')
@section('title', 'Cadastro')
@push('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
    <!-- if using RTL (Right-To-Left) orientation, load the RTL CSS file after fileinput.css by uncommenting below -->

    <!-- Ekko Lightbox -->
    <link rel="stylesheet" href="{{asset("plugins/ekko-lightbox/ekko-lightbox.css")}}">
@endpush
@section('content-header')
   Editando o catalogo {{$catalog->name }} do cliente {{ $catalog->client->name }}
@endsection

@section('content')

    <!-- Main content -->
    <div class="row">
        <div class="col-xs-12">

            <div class="box box-primary">

                @if ($errors->any())
                    <div class="card-body">
                        <div class="callout callout-danger">
                            <h5>Preencha corretamente os campos.</h5>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
            @endif

            <!-- /.box-header -->
                <!-- form start -->
                <form method="post" action="{{ route('catalogs.update', $catalog->id) }}" enctype="multipart/form-data">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <label for="name">Nome da galeria / Título</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{ $catalog->name }}" placeholder="Título da galeria">
                        </div>

                        <div class="form-group">
                            <label for="name">Nome do cliente</label>
                             <input type="text" id='name' class="form-control" value="{{ $catalog->client->name }}" disabled>
                        </div>

                        <!-- Main content -->
                        <section class="content">
                            <div class="container-fluid">
                                <div class="row">

                                    <div class="col-12">
                                        <div class="card card-primary">

                                            <div class="card-body">
                                                <div class="row">
                                                    @foreach ($catalog->attachments()->get() as $photo)
                                                    <div class="col-sm-2">
                                                        <div style="height: 150px;">
                                                        <a href="{{ asset('storage/public/'.$photo->path) }}" data-toggle="lightbox" data-title="sample 1 - white" data-gallery="gallery">
                                                            <img src="{{ asset('storage/public/'.$photo->path) }}" class="img-fluid mb-2" alt="white sample" width="150px">
                                                        </a>
                                                        </div>
                                                        <input type="text" class="form-control" name="fileDescription[id][]"><br>
                                                        <a href=""><i class="fa fa-trash"></i></a>
                                                    </div>
                                                    @endforeach
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- /.container-fluid -->
                        </section>
                        <!-- /.content -->


                        <br><br>
                  <input type="submit" class="btn btn-block btn-success" value="CADASTRAR">
                </form>


            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    @push('scripts')

            <!-- optionally if you need translation for your language then include  locale file as mentioned below -->
        <!-- Ekko Lightbox -->
            <script src="{{asset("plugins/ekko-lightbox/ekko-lightbox.min.js")}}"></script>
                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <!-- piexif.min.js is needed for auto orienting image files OR when restoring exif data in resized images and when you
                    wish to resize images before upload. This must be loaded before fileinput.min.js -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/piexif.min.js" type="text/javascript"></script>
                <!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview.
                    This must be loaded before fileinput.min.js -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/sortable.min.js" type="text/javascript"></script>
                <!-- purify.min.js is only needed if you wish to purify HTML content in your preview for
                    HTML files. This must be loaded before fileinput.min.js -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/purify.min.js" type="text/javascript"></script>
                <!-- popper.min.js below is needed if you use bootstrap 4.x. You can also use the bootstrap js
                   3.3.x versions without popper.min.js. -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
                <!-- bootstrap.min.js below is needed if you wish to zoom and preview file content in a detail modal
                    dialog. bootstrap 4.x is supported. You can also use the bootstrap js 3.3.x versions. -->
                <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" type="text/javascript"></script>
                <!-- the main fileinput plugin file -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/fileinput.min.js"></script>

                <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/locales/pt-BR.js"></script>

                <script>

                $(function () {

                    $(document).on('click', '[data-toggle="lightbox"]', function(event) {
                        event.preventDefault();
                        $(this).ekkoLightbox({
                            alwaysShowClose: true
                        });
                    });

                    $('.filter-container').filterizr({gutterPixels: 3});
                    $('.btn[data-filter]').on('click', function() {
                        $('.btn[data-filter]').removeClass('active');
                        $(this).addClass('active');
                    });
                })
            </script>
        @if ($errors->any())
            {!! toastr()->error('Houve um erro no cadastro', 'Atenção')->render() !!}
        @endif
    @endpush
@endsection

resources/views/admin/catalogs/index.blade.php
@extends('layouts.admin.app')
@section('title', 'Cadastro')
    @push('styles')
        <link rel="stylesheet" href="{{ asset("css/dataTables.bootstrap.min.css") }}">
    @endpush
@section('content-header')
    Catálogos
@endsection

@section('content')

    <!-- Main content -->
        <div class="row">
            <div class="col-xs-12">

                <div class="box">
                    <div class="box-header">
                        <a href="{{ route('catalogs.create') }}" class="btn btn-block btn-info">  <i class="fa fa-edit"></i> ADICIONAR UM NOVO CATÁLOGO</a>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Cliente</th>
                                <th>Galeria</th>
                                <th>Ações</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($catalogs as $catalog)
                            <tr>


                                <td>{{ $catalog->name }}</td>
                                <td>{{ $catalog->client->name }}</td>
                                <td> {{ $catalog->attachments->count() }} imagens </td>
                                <td>
                                    <a class="btn btn-sm" href="{{ route('catalogs.edit', $catalog->id) }}"> <i class="fa fa-edit"></i>  </a>
                                    <a class="btn btn-sm"  data-toggle="modal" data-target="#iconModal-{{ $catalog->id }}"> <i class="fa fa-trash"></i>  </a>


                                    <div class="modal fade text-xs-left" id="iconModal-{{ $catalog->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                    <h4 class="modal-title" id="myModalLabel2"><i class="icon-warning2"></i> Confirma operação</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Você tem certeza que quer <strong>apagar</strong> este catálogo ?</p>

                                                    <h5>Lembre-se que os clientes atrelados à ela serão ocultados no site.</h5>

                                                </div>
                                                <div class="modal-footer">
                                                    <form method="POST" action="{{ route('catalogs.destroy', $catalog->id) }}">
                                                    @method('DELETE')
                                                        @csrf
                                                    <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Fechar</button>
                                                    <button type="submit" class="btn btn-outline-primary">Deletar</button>
                                                    </form>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    @push('scripts')
        @if (session('message'))
            {!! toastr()->info(session('message'), 'Atenção')->render() !!}
        @endif
    @endpush
    @endsection