routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('commands/{command}', function($command) {
    try {
        \Illuminate\Support\Facades\Artisan::call($command);
    } catch(\Exception $e){
        dd($e->getMessage());
    }

    echo \Illuminate\Support\Facades\Artisan::output();
});

Route::get('image_show/{filename}', 'ImageController@displayImage')->name('image.show');

// ROTAS DO SITE
Route::group(['prefix'=>'/', 'namespace' => 'Home', 'as' => 'home.'], function() {
    Route::get('/', ['uses' => 'SiteController@index'])->name('index');
    Route::post('/busca', ['uses' => 'SiteController@search'])->name('search');
    Route::get('{client}/detalhes/', ['uses' => 'SiteController@details'])->name('details');
    Route::get('projeto/{slug}', ['uses' => 'SiteController@projectDetail'])->name('project.details');
    Route::get('/contato', ['uses' => 'SiteController@contact'])->name('contact');
    Route::get('/quem-somos', ['uses' => 'SiteController@about'])->name('about');
    Route::get('/projetos', ['uses' => 'SiteController@projects'])->name('projects');
    Route::get('/registro', ['uses' => 'SiteController@register'])->name('register');
    Route::get('/categorias', ['uses' => 'SiteController@categories'])->name('categories');
    Route::get('/categorias/{slug}', ['uses' => 'SiteController@category'])->name('category');
    Route::get('politica-de-privacidade', ['uses' => 'SiteController@policies'])->name('policies');
    Route::get('termos-de-uso', ['uses' => 'SiteController@terms'])->name('terms');
});



Auth::routes();

// ROTAS DO DASH ADMIN
Route::group(['prefix'=>'/admin',  'namespace' => 'Admin', 'middleware' => ['auth']], function() {

    Route::get('/', ['as' => 'admin.dash', 'uses' => 'AdminController@index']);

    Route::resource('/clients', 'ClientsController');

    Route::resource('/advertisements', 'AdvertisementsController');

    Route::resource('/users', 'UsersController');

    Route::resource('/payments', 'PaymentsController');

    Route::resource('/categories', 'CategoriesController');

    Route::resource('/contracts', 'ContractsController');

    Route::resource('/catalogs', 'CatalogsController');

    Route::resource('/configs', 'ConfigsController');

    Route::resource('/usefuls', 'UsefulsController');

    Route::resource('/projects', 'ProjectsController');
});


Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/admin/app.blade.php
@include('layouts.admin.header')

    @include("layouts.admin.menus")
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <section class="content-header">
            <h1>
               @yield('content-header')
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Tables</a></li>
                <li class="active">Data tables</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
                @yield('content')
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->



<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.4.13
    </div>
    <strong>Copyright &copy; {{ date('Y') }} <a href="http://www.hojecachoeira.com.br">Hoje!Cachoeira</a>.</strong>
    Todos os direitos reservados.
</footer>

@include('layouts.admin.footer')

resources/views/layouts/admin/auth.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">


    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset("plugins/fontawesome-free/css/all.min.css") }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset("css/ionicons.min.css")}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset("plugins/icheck-bootstrap/icheck-bootstrap.min.css")}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset("css/alt/adminlte.min.css")}}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">


<div class="login-box">
    <div class="login-logo">
        <b>Hoje</b> em cachoeira
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Portal de oportunidades !</p>


        @yield('content')


    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->


<!-- jQuery 3 -->
<script src="{{ asset("plugins/jquery/jquery.min.js") }}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset("plugins/bootstrap/js/bootstrap.bundle.min.js") }}"></script>

<script src="{{ asset("js/adminlte.min.js") }}"></script>

</body>
</html>

resources/views/layouts/admin/footer.blade.php
<!-- jQuery 3 -->
<script src="{{ asset("plugins/jquery/jquery.min.js") }}"></script>


<!-- Bootstrap 3.3.7 -->
<script src="{{ asset("js/bootstrap.min.js") }}"></script>
<!-- DataTables -->
<script src="{{ asset("js/jquery.dataTables.min.js") }}"></script>
<script src="{{ asset("js/dataTables.bootstrap.min.js") }}"></script>
<!-- SlimScroll -->
<script src="{{ asset("js/jquery.slimscroll.min.js") }}"></script>
<!-- FastClick -->
<script src="{{ asset("js/fastclick.js") }}"></script>
<script src="{{asset("plugins/toastr/toastr.min.js")}}"></script>

<!-- AdminLTE App -->
<script src="{{ asset("js/adminlte.min.js") }}"></script>
<script src="{{ asset("js/jquery.mask.min.js") }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset("js/demo.js") }}"></script>

@stack('scripts')
<!-- page script -->
<script>
    $(function () {
        $('#example1').DataTable()
        $('#example2').DataTable({
            'paging'      : true,
            'lengthChange': false,
            'searching'   : false,
            'ordering'    : true,
            'info'        : true,
            'autoWidth'   : false
        })
    })
</script>


</body>
</html>

resources/views/layouts/admin/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>Hoje em Cachoeira | Administração</title>



    <link rel="stylesheet" href="{{ asset("css/bootstrap.min.css") }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset("css/font-awesome.min.css") }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset("css/ionicons.min.css") }}">
    <!-- Toastr -->
    <link rel="stylesheet" href="{{ asset("plugins/toastr/toastr.min.css")}}">

    @stack('styles')

    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset("css/AdminLTE.min.css") }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset("css/skins/_all-skins.min.css") }}">


</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="{{ route('admin.dash') }}" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>H</b>AD</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Hoje</b>ADMIN</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">



                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">

                            <span class="hidden-xs">Olá {{ Auth::user()->name }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <p>
                                    Administrador
                                    <small> - </small>
                                </p>
                            </li>
                            <!-- Menu Body -->

                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="" class="btn btn-default btn-flat">Perfil</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">Sair</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->
                    <li>
                        <a href="{{ route('configs.index') }}" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

resources/views/layouts/admin/menus.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">

            <li>
                <a href="{{ route('admin.dash') }}">
                    <i class="fa fa-dashboard"></i> <span>Painel</span>
                    <span class="pull-right-container">   </span>
                </a>
            </li>
            <li class="header">OPERACIONAL</li>
            <li class="active">
                <a href="{{ route('contracts.index') }}">
                    <i class="fa fa-bullhorn"></i> <span>Contratos</span>
                    <span class="pull-right-container">    </span>
                </a>
            </li>
            <li>
                <a href="{{ route('usefuls.index') }}">
                    <i class="fa fa-book"></i> <span>Úteis</span>
                    <span class="pull-right-container">    </span>
                </a>
            </li>
            <li>
                <a href="{{ route('clients.index') }}">
                    <i class="fa fa-users"></i> <span>Clientes</span>
                    <span class="pull-right-container">    </span>
                </a>
            </li>
            <li>
                <a href="{{ route('catalogs.index') }}">
                    <i class="fa fa-shopping-cart"></i> <span>Catálogo</span>
                    <span class="pull-right-container">    </span>
                </a>
            </li>
            <li>
                <a href="{{ route('users.index') }}">
                    <i class="fa fa-users"></i> <span>Usuários do sistema</span>
                    <span class="pull-right-container">   </span>
                </a>
            </li>
            <li>
                <a href="{{ route('projects.index') }}">
                    <i class="fa fa-certificate"></i> <span>Projetos</span>
                    <span class="pull-right-container">   </span>
                </a>
            </li>
            <li class="header">CONFIGURAÇÕES</li>
            <li>
                <a href="{{ route('advertisements.index') }}">
                    <i class="fa fa-credit-card"></i> <span>Plano de negócios</span>
                    <span class="pull-right-container">   </span>
                </a>
            </li>
            <li>
                <a href="{{ route('payments.index') }}">
                    <i class="fa fa-barcode"></i> <span>Formas de pagamentos</span>
                    <span class="pull-right-container">    </span>
                </a>
            </li>
            <li>
                <a href="{{ route('categories.index') }}">
                    <i class="fa fa-cube"></i> <span>Categorias do site</span>
                    <span class="pull-right-container">   </span>
                </a>
            </li>

        </ul>
    </section>
    <!-- /.sidebar -->
</aside>